#spring.jpa.hibernate.ddl-auto=create
#spring.datasource.jdbcUrl=jdbc:mysql://10.0.0.100:3306/CLIENT_DATA
#spring.datasource.driverClassName=com.mysql.jdbc.Driver
#spring.datasource.username=paulina
#spring.datasource.password=passpass
spring:
  datasource:
    client_data:
        jdbcUrl: jdbc:mysql://10.0.0.100:3306/CLIENT_DATA
        driverClassName: com.mysql.jdbc.Driver
        username: paulina
        password: passpass

mybatis:
  typeAliasesPackage: com.rami.mybatismappers
  mapperLocations: classpath*:**/mappers/*.xml


